Vagrant.configure("2") do |config|
    config.vm.box = "MaxFedotov/orchestrator-agent-test-percona57"
    config.vm.box_version = "0.0.2"
    config.vm.synced_folder "../../vagrant/", "/vagrant", type: "nfs"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 2
    end
    config.vm.hostname = ENV["hostname"]
    config.vm.network "private_network" , ip: ENV["ip"]

end