Vagrant.configure("2") do |config|
    config.vm.box = "MaxFedotov/orchestrator-agent-test-percona80"
    config.vm.box_version = "0.0.2"
    config.vm.define ENV["hostname"] do |host|
        host.vm.synced_folder "../../shared/", "/vagrant", type: "nfs"
        host.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 2
        end
        host.vm.hostname = ENV["hostname"]
        host.vm.network "private_network" , ip: ENV["ip"]
        host.vm.provision "shell", inline: "sudo bash -c \"echo 'export GOPATH=/home/vagrant/go' >> /etc/profile.d/myvars.sh\""
    end
end